services:
  backend:
    build:
      context: ./backend
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: rbm_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rbm_user
      MYSQL_PASSWORD: rbm_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysq
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './frontend/dist:/usr/share/nginx/html'
    depends_on:
      - backend
    networks:
      - dev

networks:
  dev:

volumes:
  mysql_data: