services:
  backend:
    build:
      context: ./backend
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: rbm_db
      MYSQL_USER: rbm_user
      MYSQL_PASSWORD: rbm_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './frontend/dist:/usr/share/nginx/html'
    depends_on:
      - backend
    networks:
      - dev

networks:
  dev:
