services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./static:/static
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_dist:/app/dist
    networks:
      - dev

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: rbm_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rbm_user
      MYSQL_PASSWORD: rbm_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
      - './nginx.conf:/etc/nginx/nginx.conf'
      - ./static:/static
      - ./backend/media:/media
    depends_on:
      - backend
    networks:
      - dev

networks:
  dev:

volumes:
  mysql_data:
  frontend_dist:
