# Generated by Django 5.2 on 2025-05-27 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lead_time', models.IntegerField(help_text='Время выполнения в минутах')),
                ('price_per_m2', models.DecimalField(decimal_places=2, help_text='Цена за м²', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20, null=True)),
                ('square_meters', models.PositiveIntegerField(default=0)),
                ('entrance', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('average_rating', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='backend_company.cleaningcompany')),
            ],
        ),
        migrations.CreateModel(
            name='OrderClining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Принятый'), ('completed', 'Завершенён'), ('canceled', 'Отменён')], default='new', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cleaning_date', models.DateField(blank=True, null=True)),
                ('cleaning_time', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Наличная'), ('card', 'Картой'), ('kaspi_qr', 'Kaspi QR')], default='cash', max_length=20)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_token_created', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('additional_services', models.ManyToManyField(blank=True, to='backend_company.additionalservice')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_company.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_company.cleaningcompany')),
            ],
        ),
    ]
